universe = vanilla
getenv = true

executable = /home/sdsmith5/Files/2_cutadapt.sh

log = Logs/$(Cluster).log
error = Logs/$(Cluster).$(Process).err

arguments = $(fastq)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = Programs/cutadapt.tar.gz, Files/source_file.sh

request_cpus = 1
request_memory = 4GB
request_disk = 1GB

Requirements = (Target.HasGluster == true)

queue fastq from /mnt/gluster/sdsmith5/keys/reads.list
