universe = vanilla
getenv = true

executable = /home/sdsmith5/Files/5_indel_sites.sh

log = Logs/$(Cluster).log
error = Logs/$(Cluster).$(Process).err

arguments = $(region)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = Programs/GATK.tar.gz, Files/source_file.sh

request_cpus = 1
request_memory = 2GB
request_disk = 1GB

Requirements = (Target.HasGluster == true)

queue region from /mnt/gluster/sdsmith5/keys/bamfile.list