universe = vanilla
getenv = true

executable = /home/sdsmith5/Files/6_interval_calls.sh

log = Logs/$(Cluster).log
error = Logs/$(Cluster).$(Process).err

arguments = $(int)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = Programs/GATK.tar.gz, Files/source_file.sh 

request_cpus = 1
request_memory = 4GB
request_disk = 1GB

Requirements = (Target.HasGluster == true)

queue int from /mnt/gluster/sdsmith5/keys/realigned_bams.list
